# =============================================================
# Figure 5: Steady-state friction F_ss(V) for alpha = 1.5, 2.0, and 3.0.
#
# The input files are generated by steady_state_friction.c.
#
#  Data files:
#    Fss_alpha1.5.txt
#    Fss_alpha2.0.txt
#    Fss_alpha3.0.txt
#
#  Column 1 : V
#  Column 2 : F_ss(V)
#
# Run from this directory: gnuplot load.plt
# Output: fig/Fss_vs_Vtau_over_Lmin.pdf
# =============================================================

system "mkdir -p fig"

# ----- output -----
set encoding utf8
set terminal pdfcairo enhanced font "Times-New-Roman,30" size 16cm,12cm
set output "fig/Fss_vs_Vtau_over_Lmin.pdf"

# ----- axis labels -----
set xlabel "V" offset 0,0
set ylabel "F_{ss}(V)/f_0" offset 0,0
set lmargin 10

# ----- axes -----
set logscale x 10
unset logscale y
set yrange [0:10]
set xrange [1e-5:1e6]
set format x "10^{%L}"
set xtics 10
set mxtics 10
set ytics 0,2,10

# ----- ticks and legend -----
set ytics font "Times New Roman,30"
set xtics font "Times New Roman,23"
set key top right font "Times-New-Roman,20" offset 0,-1

# ----- colors -----
c_a15 = "#D55E00"   # alpha = 1.5 : vermillion
c_a20 = "#0072B2"   # alpha = 2.0 : blue
c_a30 = "#009E73"   # alpha = 3.0 : green
c_guide = "#444444" # guideline

# ----- data files -----
file_a15 = "data/Fss_alpha1.5.txt"
file_a20 = "data/Fss_alpha2.0.txt"
file_a30 = "data/Fss_alpha3.0.txt"

# ----- guideline: const. - f0 Phi c log(V) -----
f0   = 1.0
Phi  = 0.5
c    = 1.0
GXMIN = 1e-5
GXMAX = 1e-2
Cguide = 3      # <- adjust this constant as you like
guide(x) = (x > GXMIN && x < GXMAX) \
           ? Cguide - f0*Phi*c*log(x) \
           : 1/0


# ----- vertical guide lines -----
set arrow 1 from 1e-2, graph 0 to 1e-2, graph 1 \
    nohead dt 2 lw 2 lc rgb "#8C8CFF"

set arrow 2 from 1e3, graph 0 to 1e3, graph 1 \
    nohead dt 2 lw 2 lc rgb "#8C8CFF"


# =============================================================
#  plot
# =============================================================
plot \
    file_a15 using 1:2 w l lw 3 lc rgb c_a15 title "{/Symbol a}=1.5", \
    file_a20 using 1:2 w l lw 3 lc rgb c_a20 title "{/Symbol a}=2.0", \
    file_a30 using 1:2 w l lw 3 lc rgb c_a30 title "{/Symbol a}=3.0", \
    guide(x) w l dt 2 lw 2.5 lc rgb c_guide notitle

unset output
