# =============================================================
# Figure 3: Contact-time distributions after a velocity step.
#
# This script plots the five datasets generated by
# contact_time_distribution.c on logarithmic axes:
#     ptheta_t0.txt
#     ptheta_t1em3.txt
#     ptheta_t1em1.txt
#     ptheta_t10.txt
#     ptheta_t1000.txt
#
# Run from this directory: gnuplot load.plt
# Output: fig/ptheta_distribution_16x12.pdf
# =============================================================

system "mkdir -p fig"

set encoding utf8
set terminal pdfcairo enhanced color font "Times New Roman,18" size 16cm,12cm
set output "fig/ptheta_distribution_16x12.pdf"

# -------------------------------------------------------------
# Axes
# -------------------------------------------------------------

set logscale xy

# LMAX=1e3, V1=0.1 のため、
# t=0 における最大接触時間は LMAX/V1=1e4
set xrange [1e-4:2e4]
set yrange [1e-6:1e0]

set format x "10^{%T}"
set format y "10^{%T}"

set xtics font "Times New Roman,30"
set ytics font "Times New Roman,30"

set mxtics 10
set mytics 10

set xlabel "{/Symbol q}"
set ylabel "P_t({/Symbol q})"

# -------------------------------------------------------------
# Legend
# -------------------------------------------------------------

set key left bottom font "Times New Roman,20"
set key spacing 1.10
set key samplen 2.5
set key reverse Left

# -------------------------------------------------------------
# Margins
# -------------------------------------------------------------

set lmargin 10
set bmargin 4
set tmargin 2
set rmargin 4

# -------------------------------------------------------------
# Line styles
# -------------------------------------------------------------

set style line 11 lc rgb "#3b4cc0" lw 5    # t/tau = 0
set style line 12 lc rgb "#6889e8" lw 5    # t/tau = 1e-3
set style line 13 lc rgb "#9dbdff" lw 5    # t/tau = 1e-1
set style line 14 lc rgb "#f4c96a" lw 5    # t/tau = 10
set style line 15 lc rgb "#b40426" lw 5    # t/tau = 1000

set style line 21 lc rgb "black" lw 2.5 dt 2  # guideline

# -------------------------------------------------------------
# Power-law guideline: theta^(1-alpha)
# -------------------------------------------------------------

ALPHA = 1.5
Cg    = 0.05

GXMIN = 1e-2
GXMAX = 1e2

guide(x) = (x > GXMIN && x < GXMAX) \
           ? Cg * x**(1.0-ALPHA) \
           : 1/0


# -------------------------------------------------------------
# Remove zero or negative values for log-scale plotting
# -------------------------------------------------------------

vx(x,y) = (x > 0.0 && y > 0.0) ? x : 1/0
vy(x,y) = (x > 0.0 && y > 0.0) ? y : 1/0

# -------------------------------------------------------------
# Plot
# -------------------------------------------------------------

plot \
    "data/ptheta_t0.txt" \
        u (vx($1,$2)):(vy($1,$2)) \
        w l ls 11 title "t/{/Symbol t}=0", \
    "data/ptheta_t1em3.txt" \
        u (vx($1,$2)):(vy($1,$2)) \
        w l ls 12 title "t/{/Symbol t}=10^{-3}", \
    "data/ptheta_t1em1.txt" \
        u (vx($1,$2)):(vy($1,$2)) \
        w l ls 13 title "t/{/Symbol t}=10^{-1}", \
    "data/ptheta_t10.txt" \
        u (vx($1,$2)):(vy($1,$2)) \
        w l ls 14 title "t/{/Symbol t}=10", \
    "data/ptheta_t1000.txt" \
        u (vx($1,$2)):(vy($1,$2)) \
        w l ls 15 title "t/{/Symbol t}=10^{3}", \
    guide(x) \
        w l ls 21 notitle

unset output
