# =============================================================
# Figure 2: Friction relaxation after a velocity step.
#
# The colored curves show finite-N simulations generated by
# finite_n_relaxation.c. The black curve is the N -> infinity result generated
# by analytic_relaxation.c.
#
# Run from this directory: mkdir -p fig && gnuplot load.plt
# Output: fig/fig2.pdf
# =============================================================

system "mkdir -p fig"

# ----- 出力設定 -----
set encoding utf8
set terminal pdfcairo enhanced font "Times-New-Roman,30" size 16cm,12cm
set output "fig/fig2.pdf"

# ----- 軸ラベル -----
set xlabel "t/{/Symbol t}" offset 0,0
set ylabel "F/f_0" offset 0,0
set lmargin 10

# ----- 軸設定 -----
unset logscale x
unset logscale y
#set xrange [-5:15]
#set yrange [0.8:1.7]
set ytics 0.2

# ----- 目盛り・凡例 -----
set tics font "Times New Roman,32"
set key top right font "Times-New-Roman,20" offset 0,-1

# ----- 線・点の設定 -----
# 視認性を上げるため、高コントラストな配色に変更
c_N1 = "#D55E00"   # N = 10^3  : vermillion
c_N2 = "#0072B2"   # N = 10^4  : blue
c_N3 = "#009E73"   # N = 10^5  : green
c_th = "#000000"   # N -> infinity

# ----- 定常値ガイドライン -----
#  N -> infinity の解析式の極限値（このパラメータでの値）。
#    F_ss(V1) : 速度ステップ直前（t=0）の定常値
#    F_ss(V2) : 速度ステップ後（t->infinity）の定常値
Fss1 = 3.645897955824   # F_ss(V1=0.1)
Fss2 = 2.554884362808  # F_ss(V2=1.0)
c_g  = "#888888"  # ガイドラインの色

set arrow 1 from -500,Fss1 to 2000,Fss1 nohead dt 3 lw 1.5 lc rgb c_g front
set arrow 2 from -500,Fss2 to 2000,Fss2 nohead dt 3 lw 1.5 lc rgb c_g front
#set label 1 "F_{ss}(V_1)" at 0.8,Fss1-0.035 left font "Times-New-Roman,18" tc rgb c_g front
#set label 2 "F_{ss}(V_2)" at 0.8,Fss2-0.035 left font "Times-New-Roman,18" tc rgb c_g front

# ----- データファイル -----
file_N1 = "data/F_alpha1.5_lmin0.01_lmax1e+03_N1000_dt0.1.txt"
file_N2 = "data/F_alpha1.5_lmin0.01_lmax1e+03_N10000_dt0.1.txt"
file_N3 = "data/F_alpha1.5_lmin0.01_lmax1e+03_N100000_dt0.1.txt"
file_th = "data/F_Ninfty_alpha1.5_lmin0.01_lmax1e+03_V10.1_V21_dt1_dtheta0.1.txt"

# =============================================================
#  描画
# =============================================================
#  t=0 は除き、t>0 の緩和過程を比較する。
#  有限Nは線（間引きなし・全点）、N -> infinity は破線で表示する。
# =============================================================

plot \
    file_N1 every 20 using 1:2 w l lw 2 lc rgb c_N1 title "Simulation N=10^{3}", \
    file_N2 every 20 using 1:2 w l lw 2 lc rgb c_N2 title "Simulation N=10^{4}", \
    file_N3 every 20 using 1:2 w l lw 2 lc rgb c_N3 title "Simulation N=10^{5}", \
    file_th using 1:2 w l lw 3 lc rgb c_th title "N→∞ (analytic)"

unset output
